name: pluginDeTest
version: 1.0
author: MarcJus
main: fr.marcjus.plugindetest.pluginDeTest
commands:
  test:
    description: Ceci est une commande de test
  day:
    description: Mettre le jour
    usage: /day [monde]
    permission: day.use
  night:
    description: Mettre la nuit
    usage: /night [monde]
    permission: night.use
  gm:
    description: Change le mode de jeu
    usage: /gm <mode> [joueur]
    permission: gm.use
permissions:
  day.use:
          description: Mettre le jour
          default: op
  night.use:
          description: Mettre la nuit
          default: op
  gm.use:
          description: Change le mode de jeu
          default: op
  


    
